[package]
name = "pzeudo"
version = "0.0.2-dev.1"
edition = "2024"
license = "MIT"
description = "a Deep Learning library"
keywords = ["AI", "machine-learning", "deep-learning", "neural-network", "tensor"]

[lib]
path = "./src/pzeudo/mod.rs"

[dependencies]
matrixmultiply = "0.3.10"
num-traits = "0.2.19"
rand = "0.10.2"
rand_distr = "0.6.0"
serde = {version = "1.0.229", features = ["derive"]}
serde_json = "1.0.151"
